---
id: Cli_Application
name: Cli_Application
full: Library for creating command line applications
description: A library that builds a complete command line application.
list: dev
type: library
authors:
  - name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  - name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 2.0.0
  api: 2.0.0alpha1
state:
  release: stable
  api: alpha
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7 || ^8
    composer:
      horde/argv: ^3
      horde/cli: ^3
autoload:
  classmap:
    - lib/
vendor: horde
keywords: null
ci-platform:
  '8.0':
    - php: ^8
    - ext-dom
  '8.1':
    - php: ^8
    - ext-dom
  '8.2':
    - php: ^8
    - ext-dom
  '8.3':
    - php: ^8
    - ext-dom
  '8.4':
    - php: ^8
    - ext-dom
  '8.5':
    - php: ^8
    - ext-dom
  '8.6':
    - php: ^8
    - ext-dom
ci-platform-flags:
  needs_installer_plugin: false
